# Generated by Django 2.2.8 on 2020-01-16 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('PESEL', models.IntegerField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('Numer_Prawa_Jazdy', models.CharField(max_length=13)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Klient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('idPracownik', models.IntegerField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('Stanowisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('VIN', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Marka', models.CharField(max_length=45)),
                ('Model', models.CharField(max_length=45)),
                ('Dostepnosc', models.IntegerField()),
                ('CenaZaDobe', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczanie',
            fields=[
                ('idWypozyczanie', models.IntegerField(primary_key=True, serialize=False)),
                ('Data_rozpoczecia', models.DateField()),
                ('Data_zakonczenia', models.DateField()),
                ('Cena_za_wypozyczenie', models.FloatField()),
                ('Klient_PESEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wypozyczalnia_App.Klient')),
                ('Pracownik_idPracownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wypozyczalnia_App.Pracownik')),
                ('Samochod_VIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wypozyczalnia_App.Samochod')),
            ],
        ),
    ]
